from telegram.ext import ConversationHandler

# Определяем состояния
WAITING_FOR_IMAGE, WAITING_FOR_NAME, WAITING_FOR_RARITY, WAITING_FOR_STYLE, WAITING_FOR_PNAME, WAITING_FOR_USERNAME, WAITING_FOR_ACTION, WAITING_FOR_ATTEMPTS = range(8)

# Экспортируем состояния
__all__ = ['WAITING_FOR_IMAGE', 'WAITING_FOR_NAME', 'WAITING_FOR_PNAME', 'WAITING_FOR_STYLE', 'WAITING_FOR_RARITY', 'WAITING_FOR_USERNAME', 'WAITING_FOR_ACTION', 'WAITING_FOR_ATTEMPTS']
